module StaticRouter

using StringViews
using ..Types

export @routes, dispatch, AbstractApp

"""
    AbstractApp

Base type for all Ciro applications. Subtypes are generated by the `@routes` macro.
"""
abstract type AbstractApp end

"""
    dispatch(app::AbstractApp, req::Request) -> Response

Dispatch an HTTP request to the matching handler. Generated by `@routes`.
"""
function dispatch end

# --- Helper Functions ---

"""
    find_next_slash(path::AbstractString, start_idx::Int) -> Int

Scans `path` starting from `start_idx` for the next '/'.
Returns the index of the slash, or 0 if not found.
"""
@inline function find_next_slash(path::AbstractString, start_idx::Int)
    len = ncodeunits(path)
    if start_idx > len
        return 0
    end
    for i in start_idx:len
        if codeunit(path, i) == UInt8('/')
            return i
        end
    end
    return 0
end

"""
    skip_slashes(path::AbstractString, idx::Int) -> Int

Returns the index of the first non-slash character starting from `idx`.
"""
@inline function skip_slashes(path::AbstractString, idx::Int)
    len = ncodeunits(path)
    while idx <= len && codeunit(path, idx) == UInt8('/')
        idx += 1
    end
    return idx
end

function parse_route_pattern(pattern::String)
    raw_segments = split(pattern, "/", keepempty=false)
    segments = []

    for seg in raw_segments
        if startswith(seg, ":")
            push!(segments, (:variable, Symbol(seg[2:end])))
        else
            push!(segments, (:static, seg))
        end
    end
    return segments
end

# --- Macro Implementation ---

"""
    @routes AppType begin
        middleware(Logger)
        middleware(CORS)
        ("GET", "/") => index_handler
        ("POST", "/data") => data_handler
        ("GET", "/user/:id") => get_user
    end

Define a static router with compile-time middleware and route matching.
Generates a concrete `AppType <: AbstractApp` and a `dispatch` method.

Middleware is applied at macro-expansion time (no runtime `Function` storage).
Route parameters are passed as `SubString` arguments to handlers.
"""
macro routes(app_type::Symbol, block)
    routes = []
    middlewares = []

    if block.head == :block
        for line in block.args
            if line isa Expr
                # Parse middleware declarations: middleware(Func)
                if line.head == :call && line.args[1] == :middleware
                    push!(middlewares, line.args[2])
                    # Parse route declarations: ("METHOD", "/path") => handler
                elseif line.head == :call && line.args[1] == :(=>)
                    if length(line.args[2].args) == 2
                        (method, path) = line.args[2].args
                        func = line.args[3]
                        push!(routes, (method, path, func))
                    end
                end
            end
        end
    end

    fallback = :(return Response(404, "Not Found"))

    # Build the dispatch logic from bottom up (reverse order of routes)
    current_expr = fallback

    for (method, path, func) in reverse(routes)
        segments = parse_route_pattern(path)

        # Identify variables in order
        vars_to_pass = [val for (type, val) in segments if type == :variable]

        # 1. The Action: Call the handler, then apply middlewares
        # Build the call expression: handler(req, var1, var2, ...)
        handler_call = :($(esc(func))(req, $(vars_to_pass...)))

        # Wrap with middlewares (applied in reverse order so first declared = outermost)
        # Each middleware: mw(req, response) -> modified_response
        # Or mw wraps the handler: mw(handler) returns a new handler
        # We use the "wrap handler" pattern: middleware returns a closure
        # Since we're generating code at compile time, we inline the wrapping

        inner_body = quote
            local _response = $handler_call
            if !isa(_response, Response)
                _response = text(string(_response))
            end
        end

        # Apply middlewares around the handler call
        # Middleware signature: mw(req, next) where next(req) -> Response
        # We build from inside out: innermost = handler, then each mw wraps it
        for mw in reverse(middlewares)
            prev_call = inner_body
            inner_body = quote
                local _response = try
                    $(esc(mw))(req, function (_inner_req)
                        local _r = $(handler_call)
                        isa(_r, Response) ? _r : text(string(_r))
                    end)
                catch e
                    @error "Handler failed" exception = (e, catch_backtrace())
                    Response(500, "Internal Server Error")
                end
            end
        end

        # If no middlewares, just call handler with try/catch
        if isempty(middlewares)
            inner_body = quote
                local _response = try
                    local _r = $handler_call
                    isa(_r, Response) ? _r : text(string(_r))
                catch e
                    @error "Handler failed" exception = (e, catch_backtrace())
                    Response(500, "Internal Server Error")
                end
            end
        end

        # Return the response
        route_body = quote
            $inner_body
            return _response
        end

        # 2. Final Check: Ensure we consumed the entire path
        route_body = quote
            if idx > len
                $route_body
            end
        end

        # 3. Match Segments (Reverse)
        for (seg_type, val) in reverse(segments)
            if seg_type == :static
                seg_str = val
                route_body = quote
                    end_idx = StaticRouter.find_next_slash(req.path, idx)
                    if end_idx == 0
                        end_idx = len + 1
                    end

                    seg_len = end_idx - idx

                    if seg_len == $(length(seg_str)) &&
                       (view(req.path, idx:end_idx-1) == $seg_str)

                        idx = end_idx
                        idx = StaticRouter.skip_slashes(req.path, idx)

                        $route_body
                    end
                end
            else
                # Variable segment
                var_sym = val
                route_body = quote
                    end_idx = StaticRouter.find_next_slash(req.path, idx)
                    if end_idx == 0
                        end_idx = len + 1
                    end

                    if idx < end_idx
                        $(var_sym) = view(req.path, idx:end_idx-1)

                        idx = end_idx
                        idx = StaticRouter.skip_slashes(req.path, idx)

                        $route_body
                    end
                end
            end
        end

        # 4. Method Check and Initialization
        current_expr = quote
            if req.method == $method
                idx = 1
                len = ncodeunits(req.path)
                idx = StaticRouter.skip_slashes(req.path, idx)
                $route_body
            end

            $current_expr
        end
    end

    # Return the Type definition and the dispatch function
    quote
        struct $(esc(app_type)) <: StaticRouter.AbstractApp end

        function StaticRouter.dispatch(::$(esc(app_type)), req::Request)
            $current_expr
        end
    end
end

end
